version: "3.0"

services:
  api:
    container_name: "api"
    volumes:
      - ./app:/app
    build: .
    ports:
      - 8080:8080
  db:
    image: mysql:latest
    volumes:
      - ./temp/db-data:/var/lib/mysql
    environment:
      - ENV=ja_JP.UTF-8
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=test_user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=test_database
